### ISSUE TITLE
Scope:all using to upload seed data

### ISSUE THREAD

**Issue by oleksandr-diudiun** [db-migrate/english-docs#8] opened 2016-03-10 08:37 UTC
So I have some seed data migrations in subfolder "migrations/data" and want to apply this migrations with schema migrations from "migrations" folder. 

What i need?
run migrate up:all (on some dev or test environment) and apply migrations from "migrations" and "migrations/data" folders ordered by timestamp in file names

For example: 
1. apply table1 schema from migrations
2. apply table1 seed data from migrations/data
3. apply table1 schema changes from migrations
4. apply table1 additional seed data from migrations/data

Current problem:
all migrations now applies from root folder "migrations" at first, than from each subfolder ordered desk by subfolders names.

So if i have an old schema with old seed data, I cant create schema changes on this table because when I will apply it on clear db, at first will be applied old schema and changes and than old seed data with expecting old schema. So i have errors.

Can we change it? or maybe I need some other workflow for this process?

**Comment by wzrdtales** [comment] 2016-03-11 16:31
duplicate of https://github.com/db-migrate/node-db-migrate/issues/357

**Closed as completed by wzrdtales** 2016-03-11 16:31 UTC
Labels: question
